(function(angular){
  angular
  .module('moviecat',[
    'ngRoute',
    'moviecat.home_page',
    'moviecat.details',
    'moviecat.movieList',
    'moviecat.search',
    'moviecat.jsonp',
    'moviecat.directives'
    ]);
})(angular)